# Generated by Django 3.0.10 on 2020-10-06 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deputy',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deputy',
            name='second_last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deputy',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='deputy',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='deputy',
            name='political_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.PoliticalGroup'),
        ),
        migrations.AlterField(
            model_name='deputy',
            name='sex',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='politicalgroup',
            name='color',
            field=models.CharField(choices=[('red', 'red')], max_length=32, null=True),
        ),
    ]
