# Generated by Django 3.0.10 on 2020-10-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20201006_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeputyLegislature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
                ('kind', models.IntegerField(choices=[(1, 'Ordinaria'), (2, 'Extraordinaria'), (3, '-')])),
            ],
        ),
    ]
