# Generated by Django 3.0.10 on 2020-10-06 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_deputylegislature'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeputySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('init_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('kind', models.IntegerField(choices=[(1, 'Ordinaria'), (2, 'Especial'), (3, 'Congreso Pleno'), (4, 'De Instalación'), (5, 'Pedida')])),
                ('status', models.IntegerField(choices=[(0, 'Citada'), (1, 'Celebrada'), (2, 'Fracasada')])),
                ('legislature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.DeputyLegislature')),
            ],
        ),
    ]
