# Generated by Django 3.0.10 on 2020-10-07 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_deputysession'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeputyVotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('date', models.DateTimeField()),
                ('quorum', models.IntegerField(choices=[(1, 'Quorum Simple'), (2, 'Quorum Calificado'), (3, 'Reforma Constitucional 2/3'), (4, 'Reforma Constitucional 3/5'), (5, 'Ley Orgánica Constitucional'), (6, 'Ley Interpretativa'), (7, '3/5'), (8, '2/5'), (9, '1/3'), (10, '2/3')])),
                ('result', models.IntegerField(choices=[(0, 'Rechazado'), (1, 'Aprobado'), (2, 'Unánime'), (3, 'Empate'), (4, 'Sin Quorum'), (9, 'Sin Resultado')])),
                ('kind', models.IntegerField(choices=[(1, 'Proyecto de Ley'), (2, 'Proyecto de Resolución'), (3, 'Proyecto de Acuerdo'), (4, 'Otros')])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.DeputySession')),
            ],
        ),
    ]
