# Generated by Django 3.0.10 on 2020-10-07 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_deputyvotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputyvotation',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='models.DeputySession'),
        ),
    ]
