# Generated by Django 3.0.10 on 2020-10-07 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_deputyvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputyvote',
            name='deputy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='models.Deputy'),
        ),
    ]
