# Generated by Django 3.0.10 on 2020-10-08 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20201007_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputyvote',
            name='votation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='models.DeputyVotation'),
        ),
        migrations.CreateModel(
            name='DeputyAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attend', models.IntegerField(choices=[(0, 'No Asiste'), (1, 'Asiste'), (2, 'Justificado')], null=True)),
                ('deputy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='models.Deputy')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='models.DeputySession')),
            ],
        ),
    ]
