# Generated by Django 3.0.10 on 2020-10-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20201008_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalgroup',
            name='color',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
